
package eagleplan;


import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


//* Used: mysql-connector-java-5.1.40-bin
    
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        DBConnect conn = new DBConnect();
        try{
        conn.GetRS("Select * from slots");
        } catch (SQLException e) {
            
        }
        initComponents();
        tblSlots.setModel(DbUtils.resultSetToTableModel(conn.rs));
        //tblSlots.setColumnModel(columnModel);
        //tblSlots.setModel(DbUtils.resultSetToTableModel(connect.rs));
    }

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAppTitle = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlSlots = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSlots = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        lblAppTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAppTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppTitle.setText("EaglePlan Version 1.1a");
        lblAppTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblSlots.setAutoCreateRowSorter(true);
        tblSlots.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblSlots.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "test", "Title 3", "Title 4"
            }
        ));
        tblSlots.setRowHeight(30);
        tblSlots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSlotsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSlots);

        javax.swing.GroupLayout pnlSlotsLayout = new javax.swing.GroupLayout(pnlSlots);
        pnlSlots.setLayout(pnlSlotsLayout);
        pnlSlotsLayout.setHorizontalGroup(
            pnlSlotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSlotsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSlotsLayout.setVerticalGroup(
            pnlSlotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSlotsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Slots", pnlSlots);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAppTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAppTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSlotsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSlotsMouseClicked

        
        //(this.tblSlots.getValueAt(tblSlots.getSelectedRow(), 1))
        
        System.out.println((this.tblSlots.getValueAt(this.tblSlots.getSelectedRow(), 0)).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSlotsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    public void MakeTable(){
        
        DBConnect connect = new DBConnect();
        
        try {
            connect.GetRS("Select s.* from slots s order by s.slot_date_time_start asc");
            connect.rs.last();
            //System.out.println("The total number of records are: " + connect.rs.getRow());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Problem: " + e);
        }
            
        
        try {
            while (connect.rs.next()) {
                String id = connect.rs.getString(1);
                String location = connect.rs.getString(3);
                String Can1 = connect.rs.getString(7);
                String Can2 = connect.rs.getString(8);
                
                Object[] content = {id,location,Can1,Can2};
               
                DefaultTableModel model = new DefaultTableModel();
                
                model.addRow(content);
                
            }
        } catch (Exception e) {
            
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAppTitle;
    private javax.swing.JPanel pnlSlots;
    private javax.swing.JTable tblSlots;
    // End of variables declaration//GEN-END:variables
}
